import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../contexts/CartContext";

const geologica = Geologica({
  subsets: ["latin"],
  variable: "--font-geologica",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Limona",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geologica.variable} font-geologica antialiased`}
        suppressHydrationWarning
      >
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
